
export default [
    { id: 'q1', text: 'Je dis souvent oui, alors que je voudrais dire non.', score: 'escape' },
    { id: 'q2', text: 'Je défends mes droits, sans empiéter sur ceux des autres.', score: 'assertiveness' },
    { id: 'q3', text: 'Je préfère dissimuler ce que je pense ou ressens, si je ne connais pas bien la personne.', score: 'manipulation' },
    { id: 'q4', text: 'Je suis plutôt autoritaire et décidé…', score: 'attack' },
    { id: 'q5', text: 'Il est en général plus facile et habile d’agir par personne interposé que directement.', score: 'manipulation' },
    { id: 'q6', text: 'Je ne crains pas de critiquer et de dire aux gens ce que je pense.', score: 'attack' },
    { id: 'q7', text: 'Je n’ose pas refuser certaines tâches qui manifestement ne relèvent pas de mon attribution.', score: 'escape' },
    { id: 'q8', text: 'Je ne crains pas de donner mon opinion, même en face d’interlocuteurs hostiles…', score: 'assertiveness' },
    { id: 'q9', text: 'Quand il y a débat, je préfère me tenir en retrait pour voir comment cela va tourner.', score: 'manipulation' },
    { id: 'q10', text: 'On me reproche parfois d’avoir l’esprit de contradiction.', score: 'attack' },
    { id: 'q11', text: 'J’ai du mal à écouter les autres.', score: 'attack' },
    { id: 'q12', text: 'Je m’arrange pour être dans le secret des dieux ; cela m’a bien rendu service.', score: 'manipulation' },
    { id: 'q13', text: 'On me considère en général comme assez malin et habile dans les relations.', score: 'manipulation' },
    { id: 'q14', text: 'J’entretiens avec les autres des rapports fondés sur la confiance plutôt que sur la domination ou le calcul.', score: 'assertiveness' },
    { id: 'q15', text: 'Je préfère ne pas demander de l’aide à un collègue ; il risquerait de penser que je ne suis pas compétent.', score: 'escape' },
    { id: 'q16', text: 'Je suis timide et je me sens bloqué dès que je dois réaliser une action inhabituelle.', score: 'escape' },
    { id: 'q17', text: 'On me dit « soupe au lait » ; je m’énerve et cela fait rire les autres.', score: 'escape' },
    { id: 'q18', text: 'Je suis à l’aise dans les contacts « face à face ».', score: 'assertiveness' },
    { id: 'q19', text: 'Je joue assez souvent la comédie : comment faire autrement pour arriver à ses fins ?', score: 'manipulation' },
    { id: 'q20', text: 'Je suis bavard et je coupe la parole aux autres sans m’en rendre compte.', score: 'attack' },
    { id: 'q21', text: 'J’ai de l’ambition et je suis prêt à faire ce qu’il faut pour arriver.', score: 'attack' },
    { id: 'q22', text: 'Je sais en général qui il faut voir et quand il faut le voir : c’est important pour réussir.', score: 'manipulation' },
    { id: 'q23', text: 'En cas de désaccord, je recherche les compromis réalistes sur la base des intérêts mutuels.', score: 'assertiveness' },
    { id: 'q24', text: 'Je préfère « jouer cartes sur table ».', score: 'assertiveness' },
    { id: 'q25', text: 'J’ai tendance à remettre à plus tard ce que je dois faire.', score: 'escape' },
    { id: 'q26', text: 'Je laisse souvent un travail en train sans le terminer.', score: 'escape' },
    { id: 'q27', text: 'En général, je me présente tel que je suis, sans dissimuler mes sentiments.', score: 'assertiveness' },
    { id: 'q28', text: 'Il en faut beaucoup pour m’intimider.', score: 'attack' },
    { id: 'q29', text: 'Faire peur aux autres est souvent un bon moyen de prendre le pouvoir.', score: 'attack' },
    { id: 'q30', text: 'Quand je me suis fait avoir une fois, je sais prendre ma revanche à l’occasion', score: 'attack' },
    { id: 'q31', text: 'Pour critiquer quelqu’un, il est efficace de lui reprocher de ne pas suivre ses propres principes. Il est forcément d’accord.', score: 'manipulation' },
    { id: 'q32', text: 'Je sais tirer parti du système : je suis débrouillard.', score: 'manipulation' },
    { id: 'q33', text: 'Je suis capable d’être moi-même, tout en continuant d’être accepté socialement.', score: 'assertiveness' },
    { id: 'q34', text: 'Quand je ne suis pas d’accord, j’ose le dire sans passion et me faire entendre.', score: 'assertiveness' },
    { id: 'q35', text: 'J’ai le souci de ne pas importuner les autres.', score: 'escape' },
    { id: 'q36', text: 'J’ai du mal à prendre parti et à choisir.', score: 'escape' },
    { id: 'q37', text: 'Je n’aime pas à être la seule personne de mon avis dans un groupe : dans ce cas, je préfère me taire.', score: 'escape' },
    { id: 'q38', text: 'Je n’ai pas peur de parler en public.', score: 'assertiveness' },
    { id: 'q39', text: 'La vie n’est que rapport de force et lutte.', score: 'attack' },
    { id: 'q40', text: 'Je n’ai pas peur de relever des défis dangereux et risqués.', score: 'attack' },
    { id: 'q41', text: 'Créer des conflits peut être plus efficace que réduire des tensions.', score: 'manipulation' },
    { id: 'q42', text: 'Jouer la franchise est un bon moyen pour mettre en confiance.', score: 'manipulation' },
    { id: 'q43', text: 'Je sais écouter et je ne coupe pas la parole.', score: 'assertiveness' },
    { id: 'q44', text: 'Je mène jusqu’au bout ce que j’ai décidé de faire.', score: 'assertiveness' },
    { id: 'q45', text: 'Je n’ai pas peur d’exprimer mes sentiments tels que je les ressens.', score: 'assertiveness' },
    { id: 'q46', text: 'Je sais bien faire adhérer les gens et les amener à mes idées.', score: 'manipulation' },
    { id: 'q47', text: 'Flatter tout un chacun reste encore un bon moyen d’obtenir ce que l’on veut.', score: 'manipulation' },
    { id: 'q48', text: 'J’ai du mal à maîtriser mon temps de parole.', score: 'attack' },
    { id: 'q49', text: 'Je sais manier l’ironie mordante.', score: 'attack' },
    { id: 'q50', text: 'Je suis serviable et facile à vivre ; parfois même je me fais un peu exploiter.', score: 'escape' },
    { id: 'q51', text: 'J’aime mieux observer que participer.', score: 'escape' },
    { id: 'q52', text: 'Je préfère être dans la coulisse qu’au premier rang.', score: 'escape' },
    { id: 'q53', text: 'Je ne pense pas que la manipulation soit une solution efficace.', score: 'assertiveness' },
    { id: 'q54', text: 'Il ne faut pas annoncer trop vite ses intentions, c’est maladroit.', score: 'manipulation' },
    { id: 'q55', text: 'Je choque souvent les gens par mes propos.', score: 'attack' },
    { id: 'q56', text: 'Je préfère être loup plutôt qu’agneau.', score: 'attack' },
    { id: 'q57', text: 'Manipuler les gens est souvent le seul moyen pratique pour obtenir ce que l’on veut.', score: 'manipulation' },
    { id: 'q58', text: 'Je sais en général protester avec efficacité, sans agressivité excessive.', score: 'assertiveness' },
    { id: 'q59', text: 'Je trouve que les problèmes ne peuvent être vraiment résolus sans en chercher les causes profondes.', score: 'escape' },
    { id: 'q60', text: 'Je n’aime pas me faire mal voir.', score: 'escape' },    
];